"""Implement hierarchical SaaS foundation and connection scoping

Revision ID: 1081b9169e01
Revises: 463715dfb834
Create Date: 2025-12-30 02:40:06.369030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1081b9169e01'
down_revision: Union[str, Sequence[str], None] = '463715dfb834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_nm', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_nm')
    )
    op.create_table('etl_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('team_nm', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['etl_org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etl_code_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('location_nm', sa.String(length=100), nullable=False),
    sa.Column('repo_url', sa.String(length=255), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['etl_team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('etl_connection', sa.Column('owner_type', sa.String(length=20), nullable=True))
    op.add_column('etl_connection', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('etl_job', sa.Column('code_location_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('etl_job_source_conn_nm_fkey'), 'etl_job', type_='foreignkey')
    op.drop_constraint(op.f('etl_job_target_conn_nm_fkey'), 'etl_job', type_='foreignkey')
    op.create_foreign_key(None, 'etl_job', 'etl_code_location', ['code_location_id'], ['id'])
    op.drop_column('etl_job', 'source_conn_nm')
    op.drop_column('etl_job', 'target_conn_nm')
    op.add_column('etl_user', sa.Column('org_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'etl_user', 'etl_org', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'etl_user', type_='foreignkey')
    op.drop_column('etl_user', 'org_id')
    op.add_column('etl_job', sa.Column('target_conn_nm', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('etl_job', sa.Column('source_conn_nm', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'etl_job', type_='foreignkey')
    op.create_foreign_key(op.f('etl_job_target_conn_nm_fkey'), 'etl_job', 'etl_connection', ['target_conn_nm'], ['conn_nm'])
    op.create_foreign_key(op.f('etl_job_source_conn_nm_fkey'), 'etl_job', 'etl_connection', ['source_conn_nm'], ['conn_nm'])
    op.drop_column('etl_job', 'code_location_id')
    op.drop_column('etl_connection', 'owner_id')
    op.drop_column('etl_connection', 'owner_type')
    op.drop_table('etl_code_location')
    op.drop_table('etl_team')
    op.drop_table('etl_org')
    # ### end Alembic commands ###
