"""standardize_schema_and_add_params_contract

Revision ID: 3315655e945d
Revises: 8406e311f476
Create Date: 2025-12-29 13:44:00.384278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3315655e945d'
down_revision: Union[str, Sequence[str], None] = '46919db7c573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_params_schema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_nm', sa.String(length=255), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_strict', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_nm')
    )
    op.add_column('etl_asset_status', sa.Column('creat_by_nm', sa.String(length=100), nullable=False, server_default='DAGSTER'))
    op.add_column('etl_asset_status', sa.Column('updt_by_nm', sa.String(length=100), nullable=True))
    op.add_column('etl_asset_status', sa.Column('updt_dttm', sa.DateTime(), nullable=True))
    op.alter_column('etl_asset_status', 'btch_nbr',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('etl_asset_status', 'creat_dttm',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('etl_connection', sa.Column('creat_by_nm', sa.String(length=100), nullable=False, server_default='DAGSTER'))
    op.add_column('etl_connection', sa.Column('creat_dttm', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('etl_connection', sa.Column('updt_by_nm', sa.String(length=100), nullable=True))
    op.add_column('etl_connection', sa.Column('updt_dttm', sa.DateTime(), nullable=True))
    op.drop_column('etl_connection', 'created_at')
    op.add_column('etl_job', sa.Column('creat_by_nm', sa.String(length=100), nullable=False, server_default='DAGSTER'))
    op.add_column('etl_job', sa.Column('creat_dttm', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('etl_job', sa.Column('updt_by_nm', sa.String(length=100), nullable=True))
    op.add_column('etl_job', sa.Column('updt_dttm', sa.DateTime(), nullable=True))
    # Migrate data from created_at to creat_dttm? 
    # Usually better to do: 
    # op.execute("UPDATE etl_job SET creat_dttm = created_at")
    # But for now let's keep it simple as a schema migration.
    op.drop_column('etl_job', 'created_at')
    op.add_column('etl_job_parameter', sa.Column('creat_by_nm', sa.String(length=100), nullable=False, server_default='DAGSTER'))
    op.add_column('etl_job_parameter', sa.Column('creat_dttm', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('etl_job_parameter', sa.Column('updt_by_nm', sa.String(length=100), nullable=True))
    op.add_column('etl_job_parameter', sa.Column('updt_dttm', sa.DateTime(), nullable=True))
    op.drop_column('etl_job_parameter', 'updated_at')
    op.alter_column('etl_job_status', 'creat_by_nm',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("'DAGSTER'::character varying"))
    op.alter_column('etl_job_status', 'creat_dttm',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('etl_job_status', 'updt_by_nm',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.add_column('etl_parameter', sa.Column('creat_by_nm', sa.String(length=100), nullable=False, server_default='DAGSTER'))
    op.add_column('etl_parameter', sa.Column('creat_dttm', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('etl_parameter', sa.Column('updt_by_nm', sa.String(length=100), nullable=True))
    op.add_column('etl_parameter', sa.Column('updt_dttm', sa.DateTime(), nullable=True))
    op.drop_column('etl_parameter', 'created_at')
    op.add_column('etl_schedule', sa.Column('creat_by_nm', sa.String(length=100), nullable=False, server_default='DAGSTER'))
    op.add_column('etl_schedule', sa.Column('creat_dttm', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('etl_schedule', sa.Column('updt_by_nm', sa.String(length=100), nullable=True))
    op.add_column('etl_schedule', sa.Column('updt_dttm', sa.DateTime(), nullable=True))
    op.drop_column('etl_schedule', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_schedule', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_column('etl_schedule', 'updt_dttm')
    op.drop_column('etl_schedule', 'updt_by_nm')
    op.drop_column('etl_schedule', 'creat_dttm')
    op.drop_column('etl_schedule', 'creat_by_nm')
    op.add_column('etl_parameter', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_column('etl_parameter', 'updt_dttm')
    op.drop_column('etl_parameter', 'updt_by_nm')
    op.drop_column('etl_parameter', 'creat_dttm')
    op.drop_column('etl_parameter', 'creat_by_nm')
    op.alter_column('etl_job_status', 'updt_by_nm',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('etl_job_status', 'creat_dttm',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('etl_job_status', 'creat_by_nm',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'DAGSTER'::character varying"))
    op.add_column('etl_job_parameter', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_column('etl_job_parameter', 'updt_dttm')
    op.drop_column('etl_job_parameter', 'updt_by_nm')
    op.drop_column('etl_job_parameter', 'creat_dttm')
    op.drop_column('etl_job_parameter', 'creat_by_nm')
    op.add_column('etl_job', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_column('etl_job', 'updt_dttm')
    op.drop_column('etl_job', 'updt_by_nm')
    op.drop_column('etl_job', 'creat_dttm')
    op.drop_column('etl_job', 'creat_by_nm')
    op.add_column('etl_connection', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_column('etl_connection', 'updt_dttm')
    op.drop_column('etl_connection', 'updt_by_nm')
    op.drop_column('etl_connection', 'creat_dttm')
    op.drop_column('etl_connection', 'creat_by_nm')
    op.alter_column('etl_asset_status', 'creat_dttm',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('etl_asset_status', 'btch_nbr',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('etl_asset_status', 'updt_dttm')
    op.drop_column('etl_asset_status', 'updt_by_nm')
    op.drop_column('etl_asset_status', 'creat_by_nm')
    op.drop_table('etl_params_schema')
    # ### end Alembic commands ###
