"""sync_remaining_schema_gaps

Revision ID: 3af592cd1669
Revises: e0e84631b88c
Create Date: 2025-12-29 21:00:49.392011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3af592cd1669'
down_revision: Union[str, Sequence[str], None] = 'e0e84631b88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_asset_status', sa.Column('parent_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('etl_asset_status', 'parent_asset_nm')
    op.add_column('etl_job', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'etl_job', 'etl_schedule', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'etl_job', type_='foreignkey')
    op.drop_column('etl_job', 'schedule_id')
    op.add_column('etl_asset_status', sa.Column('parent_asset_nm', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('etl_asset_status', 'parent_assets')
    # ### end Alembic commands ###
