"""add_rbac_tables

Revision ID: 463715dfb834
Revises: 3af592cd1669
Create Date: 2025-12-29 22:47:56.503923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463715dfb834'
down_revision: Union[str, Sequence[str], None] = '3af592cd1669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_nm', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_nm')
    )
    op.create_table('etl_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_nm', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['etl_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etl_user_username'), 'etl_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etl_user_username'), table_name='etl_user')
    op.drop_table('etl_user')
    op.drop_table('etl_role')
    # ### end Alembic commands ###
