"""add_blueprint_table

Revision ID: 4b8e5e9ac457
Revises: 2faff465f2fc
Create Date: 2025-12-31 13:32:32.690875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b8e5e9ac457'
down_revision: Union[str, Sequence[str], None] = '2faff465f2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_blueprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blueprint_nm', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('file_loc', sa.String(length=512), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('yaml_content', sa.Text(), nullable=True),
    sa.Column('yaml_def', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('params_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_selection', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('code_location_id', sa.Integer(), nullable=True),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['code_location_id'], ['etl_code_location.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['etl_org.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['etl_team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_nm', 'team_id', 'code_location_id', name='uq_blueprint_team_loc')
    )
    op.alter_column('etl_job_definition', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_job_def_team_location'), 'etl_job_definition', type_='unique')
    op.create_unique_constraint('uq_job_team_loc_def', 'etl_job_definition', ['job_nm', 'team_id', 'code_location_id'])
    op.add_column('etl_job_instance', sa.Column('blueprint_id', sa.Integer(), nullable=False))
    op.add_column('etl_job_instance', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('etl_job_instance', sa.Column('team_id', sa.Integer(), nullable=True))
    op.alter_column('etl_job_instance', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_job_instance_def_id'), 'etl_job_instance', type_='unique')
    op.create_unique_constraint('uq_inst_blueprint', 'etl_job_instance', ['instance_id', 'blueprint_id'])
    op.drop_constraint(op.f('etl_job_instance_job_definition_id_fkey'), 'etl_job_instance', type_='foreignkey')
    op.create_foreign_key(None, 'etl_job_instance', 'etl_blueprint', ['blueprint_id'], ['id'])
    op.create_foreign_key(None, 'etl_job_instance', 'etl_team', ['team_id'], ['id'])
    op.create_foreign_key(None, 'etl_job_instance', 'etl_org', ['org_id'], ['id'])
    op.drop_column('etl_job_instance', 'job_definition_id')
    op.drop_constraint(op.f('uq_job_instance_param'), 'etl_job_parameter', type_='unique')
    op.drop_constraint(op.f('fk_job_instance_param'), 'etl_job_parameter', type_='foreignkey')
    op.drop_column('etl_job_parameter', 'job_instance_id')
    op.drop_constraint(op.f('fk_job_instance_status'), 'etl_job_status', type_='foreignkey')
    op.drop_column('etl_job_status', 'job_instance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_job_status', sa.Column('job_instance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_job_instance_status'), 'etl_job_status', 'etl_job_instance', ['job_instance_id'], ['id'])
    op.add_column('etl_job_parameter', sa.Column('job_instance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_job_instance_param'), 'etl_job_parameter', 'etl_job_instance', ['job_instance_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_job_instance_param'), 'etl_job_parameter', ['job_instance_id'], postgresql_nulls_not_distinct=False)
    op.add_column('etl_job_instance', sa.Column('job_definition_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'etl_job_instance', type_='foreignkey')
    op.drop_constraint(None, 'etl_job_instance', type_='foreignkey')
    op.drop_constraint(None, 'etl_job_instance', type_='foreignkey')
    op.create_foreign_key(op.f('etl_job_instance_job_definition_id_fkey'), 'etl_job_instance', 'etl_job_definition', ['job_definition_id'], ['id'])
    op.drop_constraint('uq_inst_blueprint', 'etl_job_instance', type_='unique')
    op.create_unique_constraint(op.f('uq_job_instance_def_id'), 'etl_job_instance', ['job_definition_id', 'instance_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('etl_job_instance', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_column('etl_job_instance', 'team_id')
    op.drop_column('etl_job_instance', 'org_id')
    op.drop_column('etl_job_instance', 'blueprint_id')
    op.drop_constraint('uq_job_team_loc_def', 'etl_job_definition', type_='unique')
    op.create_unique_constraint(op.f('uq_job_def_team_location'), 'etl_job_definition', ['job_nm', 'team_id', 'code_location_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('etl_job_definition', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_table('etl_blueprint')
    # ### end Alembic commands ###
