"""Initial Nexus Schema

Revision ID: 4c39c260468c
Revises: 
Create Date: 2025-12-27 14:26:15.397898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c39c260468c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conn_nm', sa.String(length=255), nullable=False),
    sa.Column('conn_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conn_nm')
    )
    op.create_table('etl_job_status',
    sa.Column('btch_nbr', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('job_nm', sa.String(length=256), nullable=False),
    sa.Column('invok_id', sa.String(length=10), nullable=True),
    sa.Column('strt_dttm', sa.DateTime(), nullable=True),
    sa.Column('end_dttm', sa.DateTime(), nullable=True),
    sa.Column('btch_sts_cd', sa.CHAR(length=1), nullable=True),
    sa.Column('run_mde_txt', sa.String(length=10), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=30), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=30), nullable=True),
    sa.Column('creat_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('btch_nbr'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('etl_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parm_nm', sa.String(length=255), nullable=False),
    sa.Column('parm_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parm_nm')
    )
    op.create_table('etl_asset_status',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('btch_nbr', sa.BigInteger(), nullable=False),
    sa.Column('asset_nm', sa.String(length=256), nullable=False),
    sa.Column('parent_asset_nm', sa.String(length=256), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('partition_key', sa.String(length=255), nullable=True),
    sa.Column('dagster_event_type', sa.String(length=50), nullable=True),
    sa.Column('strt_dttm', sa.DateTime(), nullable=True),
    sa.Column('end_dttm', sa.DateTime(), nullable=True),
    sa.Column('asset_sts_cd', sa.CHAR(length=1), nullable=True),
    sa.Column('err_msg_txt', sa.Text(), nullable=True),
    sa.Column('creat_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['btch_nbr'], ['etl_job_status.btch_nbr'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etl_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_nm', sa.String(length=255), nullable=False),
    sa.Column('invok_id', sa.String(length=255), nullable=False),
    sa.Column('source_conn_nm', sa.String(length=255), nullable=True),
    sa.Column('target_conn_nm', sa.String(length=255), nullable=True),
    sa.Column('cron_schedule', sa.String(length=100), nullable=True),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_conn_nm'], ['etl_connection.conn_nm'], ),
    sa.ForeignKeyConstraint(['target_conn_nm'], ['etl_connection.conn_nm'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_nm', 'invok_id', name='uq_job_invok'),
    sqlite_autoincrement=True
    )
    op.create_table('etl_job_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etl_job_id', sa.Integer(), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etl_job_id'], ['etl_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etl_job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etl_job_parameter')
    op.drop_table('etl_job')
    op.drop_table('etl_asset_status')
    op.drop_table('etl_parameter')
    op.drop_table('etl_job_status')
    op.drop_table('etl_connection')
    # ### end Alembic commands ###
