"""Add org_code to ETLOrg

Revision ID: 5357dc4170ae
Revises: 1081b9169e01
Create Date: 2025-12-30 02:46:16.232461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5357dc4170ae'
down_revision: Union[str, Sequence[str], None] = '1081b9169e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_org', sa.Column('org_code', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'etl_org', ['org_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'etl_org', type_='unique')
    op.drop_column('etl_org', 'org_code')
    # ### end Alembic commands ###
