"""Add scoping columns to etl_schedule

Revision ID: 7637ef72d2dc
Revises: 8c2f4cde4055
Create Date: 2025-12-30 10:07:50.939846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7637ef72d2dc'
down_revision: Union[str, Sequence[str], None] = '8c2f4cde4055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add org_id as nullable first to handle existing data
    op.add_column('etl_schedule', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('etl_schedule', sa.Column('team_id', sa.Integer(), nullable=True))
    
    # Set default org_id (1) for existing schedules
    op.execute("UPDATE etl_schedule SET org_id = 1 WHERE org_id IS NULL")
    
    # Now set org_id to NOT NULL
    op.alter_column('etl_schedule', 'org_id', nullable=False)
    
    op.create_foreign_key(None, 'etl_schedule', 'etl_team', ['team_id'], ['id'])
    op.create_foreign_key(None, 'etl_schedule', 'etl_org', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'etl_schedule', type_='foreignkey')
    op.drop_constraint(None, 'etl_schedule', type_='foreignkey')
    op.drop_column('etl_schedule', 'team_id')
    op.drop_column('etl_schedule', 'org_id')
    # ### end Alembic commands ###
