"""Add partition_start_dt to etl_job

Revision ID: 8406e311f476
Revises: 3eb7404ae507
Create Date: 2025-12-28 12:09:08.376389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8406e311f476'
down_revision: Union[str, Sequence[str], None] = '3eb7404ae507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_job', sa.Column('partition_start_dt', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etl_job', 'partition_start_dt')
    # ### end Alembic commands ###
