"""Implement team-scoped roles and memberships

Revision ID: 8c2f4cde4055
Revises: a3781b26158e
Create Date: 2025-12-30 03:31:54.692910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2f4cde4055'
down_revision: Union[str, Sequence[str], None] = 'a3781b26158e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['etl_role.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['etl_team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['etl_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_user_team')
    )
    op.add_column('etl_role', sa.Column('team_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('etl_role_role_nm_key'), 'etl_role', type_='unique')
    op.create_unique_constraint('uq_team_role', 'etl_role', ['team_id', 'role_nm'])
    op.create_foreign_key(None, 'etl_role', 'etl_team', ['team_id'], ['id'])
    op.add_column('etl_user', sa.Column('default_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'etl_user', 'etl_team', ['default_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'etl_user', type_='foreignkey')
    op.drop_column('etl_user', 'default_team_id')
    op.drop_constraint(None, 'etl_role', type_='foreignkey')
    op.drop_constraint('uq_team_role', 'etl_role', type_='unique')
    op.create_unique_constraint(op.f('etl_role_role_nm_key'), 'etl_role', ['role_nm'], postgresql_nulls_not_distinct=False)
    op.drop_column('etl_role', 'team_id')
    op.drop_table('etl_team_member')
    # ### end Alembic commands ###
