"""rename_to_instance_id_and_split_params

Revision ID: 9eea77a96cc5
Revises: 4b8e5e9ac457
Create Date: 2025-12-31 15:14:04.924643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eea77a96cc5'
down_revision: Union[str, Sequence[str], None] = '4b8e5e9ac457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema with data migration."""
    # 1. etl_instance_parameter
    op.create_table('etl_instance_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_pk', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_pk'], ['etl_job_instance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['etl_org.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['etl_team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_pk')
    )

    # 2. etl_job: invok_id -> instance_id
    op.add_column('etl_job', sa.Column('instance_id', sa.String(length=255), nullable=True))
    op.execute("UPDATE etl_job SET instance_id = invok_id")
    op.alter_column('etl_job', 'instance_id', nullable=False)
    op.drop_constraint('uq_job_invok', 'etl_job', type_='unique')
    op.create_unique_constraint('uq_job_inst_id', 'etl_job', ['job_nm', 'instance_id'])
    op.drop_column('etl_job', 'invok_id')

    # 3. etl_job_status: invok_id -> instance_id
    op.add_column('etl_job_status', sa.Column('instance_id', sa.String(length=255), nullable=True))
    op.execute("UPDATE etl_job_status SET instance_id = invok_id")
    op.drop_column('etl_job_status', 'invok_id')

    # 4. etl_job_parameter: link to name/team instead of job_id
    op.add_column('etl_job_parameter', sa.Column('job_nm', sa.String(length=255), nullable=True))
    op.add_column('etl_job_parameter', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('etl_job_parameter', sa.Column('team_id', sa.Integer(), nullable=True))
    
    # Migrate data
    op.execute("""
        UPDATE etl_job_parameter p
        SET job_nm = j.job_nm,
            org_id = j.org_id,
            team_id = j.team_id
        FROM etl_job j
        WHERE p.etl_job_id = j.id
    """)
    # Note: If no job was linked, job_nm might be Null. We'll allow it for now or delete them.
    op.execute("DELETE FROM etl_job_parameter WHERE job_nm IS NULL")
    op.alter_column('etl_job_parameter', 'job_nm', nullable=False)
    
    # Drop old constraints and columns
    # Catching possible auto-naming differences
    try:
        op.drop_constraint('etl_job_parameter_etl_job_id_key', 'etl_job_parameter', type_='unique')
    except: pass
    try:
        op.drop_constraint('etl_job_parameter_etl_job_id_fkey', 'etl_job_parameter', type_='foreignkey')
    except: pass
    
    op.create_unique_constraint('uq_job_param_team', 'etl_job_parameter', ['job_nm', 'team_id'])
    op.create_foreign_key(None, 'etl_job_parameter', 'etl_team', ['team_id'], ['id'])
    op.create_foreign_key(None, 'etl_job_parameter', 'etl_org', ['org_id'], ['id'])
    op.drop_column('etl_job_parameter', 'etl_job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_job_status', sa.Column('invok_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('etl_job_status', 'instance_id')
    op.add_column('etl_job_parameter', sa.Column('etl_job_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'etl_job_parameter', type_='foreignkey')
    op.drop_constraint(None, 'etl_job_parameter', type_='foreignkey')
    op.create_foreign_key(op.f('etl_job_parameter_etl_job_id_fkey'), 'etl_job_parameter', 'etl_job', ['etl_job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_job_param_team', 'etl_job_parameter', type_='unique')
    op.create_unique_constraint(op.f('etl_job_parameter_etl_job_id_key'), 'etl_job_parameter', ['etl_job_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('etl_job_parameter', 'team_id')
    op.drop_column('etl_job_parameter', 'org_id')
    op.drop_column('etl_job_parameter', 'job_nm')
    op.add_column('etl_job', sa.Column('invok_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint('uq_job_inst_id', 'etl_job', type_='unique')
    op.create_unique_constraint(op.f('uq_job_invok'), 'etl_job', ['job_nm', 'invok_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('etl_job', 'instance_id')
    op.drop_table('etl_instance_parameter')
    # ### end Alembic commands ###
