"""Harden SaaS hierarchy with denormalized run history and scoped schemas

Revision ID: a3781b26158e
Revises: cb2cd9250140
Create Date: 2025-12-30 03:06:20.287958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3781b26158e'
down_revision: Union[str, Sequence[str], None] = 'cb2cd9250140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_team_location', 'etl_code_location', ['team_id', 'location_nm'])
    op.add_column('etl_job_status', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('etl_job_status', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'etl_job_status', 'etl_team', ['team_id'], ['id'])
    op.create_foreign_key(None, 'etl_job_status', 'etl_org', ['org_id'], ['id'])
    op.add_column('etl_params_schema', sa.Column('code_location_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('etl_params_schema_job_nm_key'), 'etl_params_schema', type_='unique')
    op.create_unique_constraint('uq_job_location_schema', 'etl_params_schema', ['job_nm', 'code_location_id'])
    op.create_foreign_key(None, 'etl_params_schema', 'etl_code_location', ['code_location_id'], ['id'])
    op.create_unique_constraint('uq_org_team', 'etl_team', ['org_id', 'team_nm'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_org_team', 'etl_team', type_='unique')
    op.drop_constraint(None, 'etl_params_schema', type_='foreignkey')
    op.drop_constraint('uq_job_location_schema', 'etl_params_schema', type_='unique')
    op.create_unique_constraint(op.f('etl_params_schema_job_nm_key'), 'etl_params_schema', ['job_nm'], postgresql_nulls_not_distinct=False)
    op.drop_column('etl_params_schema', 'code_location_id')
    op.drop_constraint(None, 'etl_job_status', type_='foreignkey')
    op.drop_constraint(None, 'etl_job_status', type_='foreignkey')
    op.drop_column('etl_job_status', 'team_id')
    op.drop_column('etl_job_status', 'org_id')
    op.drop_constraint('uq_team_location', 'etl_code_location', type_='unique')
    # ### end Alembic commands ###
