"""add_connection_config_and_type_schema

Revision ID: b3f0294a0ee1
Revises: 3315655e945d
Create Date: 2025-12-29 17:59:48.463124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3f0294a0ee1'
down_revision: Union[str, Sequence[str], None] = '3315655e945d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_conn_type_schema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conn_type', sa.String(length=50), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conn_type')
    )
    op.add_column('etl_connection', sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # Populate existing rows with empty JSON object
    op.execute("UPDATE etl_connection SET config_json = '{}' WHERE config_json IS NULL")
    # Alter column to be NOT NULL
    op.alter_column('etl_connection', 'config_json', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etl_connection', 'config_json')
    op.drop_table('etl_conn_type_schema')
    # ### end Alembic commands ###
