"""Add denormalized org_id and team_id to Jobs and Connections

Revision ID: cb2cd9250140
Revises: 5357dc4170ae
Create Date: 2025-12-30 02:58:12.910567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2cd9250140'
down_revision: Union[str, Sequence[str], None] = '5357dc4170ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_connection', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('etl_connection', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'etl_connection', 'etl_org', ['org_id'], ['id'])
    op.create_foreign_key(None, 'etl_connection', 'etl_team', ['team_id'], ['id'])
    op.add_column('etl_job', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('etl_job', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'etl_job', 'etl_team', ['team_id'], ['id'])
    op.create_foreign_key(None, 'etl_job', 'etl_org', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'etl_job', type_='foreignkey')
    op.drop_constraint(None, 'etl_job', type_='foreignkey')
    op.drop_column('etl_job', 'team_id')
    op.drop_column('etl_job', 'org_id')
    op.drop_constraint(None, 'etl_connection', type_='foreignkey')
    op.drop_constraint(None, 'etl_connection', type_='foreignkey')
    op.drop_column('etl_connection', 'team_id')
    op.drop_column('etl_connection', 'org_id')
    # ### end Alembic commands ###
