"""v1.0.0 Consolidated Schema

Revision ID: fb5aff861891
Revises: 
Create Date: 2025-12-30 21:13:53.480888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb5aff861891'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_conn_type_schema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conn_type', sa.String(length=50), nullable=False),
    sa.Column('json_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conn_type')
    )
    op.create_table('etl_org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_nm', sa.String(length=100), nullable=False),
    sa.Column('org_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_code'),
    sa.UniqueConstraint('org_nm')
    )
    op.create_table('etl_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parm_nm', sa.String(length=255), nullable=False),
    sa.Column('parm_value', sa.Text(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parm_nm')
    )
    op.create_table('etl_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('team_nm', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['etl_org.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'team_nm', name='uq_org_team')
    )
    op.create_table('etl_code_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('location_nm', sa.String(length=100), nullable=False),
    sa.Column('repo_url', sa.String(length=255), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['etl_team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'location_nm', name='uq_team_location')
    )
    op.create_table('etl_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conn_nm', sa.String(length=255), nullable=False),
    sa.Column('conn_type', sa.String(length=50), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('owner_type', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['etl_org.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['etl_team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conn_nm')
    )
    op.create_table('etl_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('role_nm', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['etl_team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'role_nm', name='uq_team_role')
    )
    op.create_table('etl_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('cron', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['etl_org.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['etl_team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('etl_job_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_nm', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('yaml_def', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('params_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_selection', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('code_location_id', sa.Integer(), nullable=True),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['code_location_id'], ['etl_code_location.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['etl_org.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['etl_team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_nm', 'team_id', 'code_location_id', name='uq_job_template_team_location')
    )
    op.create_table('etl_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_nm', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('default_team_id', sa.Integer(), nullable=True),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_team_id'], ['etl_team.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['etl_org.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['etl_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etl_user_username'), 'etl_user', ['username'], unique=True)
    op.create_table('etl_job_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_nm', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('is_singleton', sa.Boolean(), nullable=True),
    sa.Column('yaml_def', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('params_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_selection', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('cron_schedule', sa.String(length=100), nullable=True),
    sa.Column('partition_start_dt', sa.Date(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('code_location_id', sa.Integer(), nullable=True),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['code_location_id'], ['etl_code_location.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['etl_org.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['etl_schedule.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['etl_team.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['etl_job_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_nm', 'team_id', 'code_location_id', name='uq_job_def_team_location')
    )
    op.create_table('etl_team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('actv_ind', sa.Boolean(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['etl_role.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['etl_team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['etl_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_user_team')
    )
    op.create_table('etl_job_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_definition_id', sa.Integer(), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_definition_id'], ['etl_job_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_definition_id')
    )
    op.create_table('etl_job_status',
    sa.Column('btch_nbr', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('job_definition_id', sa.Integer(), nullable=True),
    sa.Column('job_nm', sa.String(length=256), nullable=False),
    sa.Column('strt_dttm', sa.DateTime(), nullable=True),
    sa.Column('end_dttm', sa.DateTime(), nullable=True),
    sa.Column('btch_sts_cd', sa.CHAR(length=1), nullable=True),
    sa.Column('run_mde_txt', sa.String(length=50), nullable=False),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_definition_id'], ['etl_job_definition.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['etl_org.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['etl_team.id'], ),
    sa.PrimaryKeyConstraint('btch_nbr'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('etl_asset_status',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('btch_nbr', sa.BigInteger(), nullable=False),
    sa.Column('asset_nm', sa.String(length=256), nullable=False),
    sa.Column('parent_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('partition_key', sa.String(length=255), nullable=True),
    sa.Column('dagster_event_type', sa.String(length=50), nullable=True),
    sa.Column('strt_dttm', sa.DateTime(), nullable=True),
    sa.Column('end_dttm', sa.DateTime(), nullable=True),
    sa.Column('asset_sts_cd', sa.CHAR(length=1), nullable=True),
    sa.Column('err_msg_txt', sa.Text(), nullable=True),
    sa.Column('creat_by_nm', sa.String(length=100), nullable=False),
    sa.Column('creat_dttm', sa.DateTime(), nullable=False),
    sa.Column('updt_by_nm', sa.String(length=100), nullable=True),
    sa.Column('updt_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['btch_nbr'], ['etl_job_status.btch_nbr'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etl_asset_status')
    op.drop_table('etl_job_status')
    op.drop_table('etl_job_parameter')
    op.drop_table('etl_team_member')
    op.drop_table('etl_job_definition')
    op.drop_index(op.f('ix_etl_user_username'), table_name='etl_user')
    op.drop_table('etl_user')
    op.drop_table('etl_job_template')
    op.drop_table('etl_schedule')
    op.drop_table('etl_role')
    op.drop_table('etl_connection')
    op.drop_table('etl_code_location')
    op.drop_table('etl_team')
    op.drop_table('etl_parameter')
    op.drop_table('etl_org')
    op.drop_table('etl_conn_type_schema')
    # ### end Alembic commands ###
